### ISSUE TITLE
stringClientHandler inside package does not work

### ISSUE THREAD

**Issue by Konard** [deep-foundation/deepcase#50]
### Describe the bug

`finderClientHandler` is opened instead of `stringClientHandler`.

https://github.com/deep-foundation/deepcase/assets/1431904/6960e20e-2ab8-4f54-bbd6-1c8aabf278ac

### Expected Behavior

`stringClientHandler` is opened.

### Current Behavior

`finderClientHandler` is opened.

### Steps to reproduce

1. Create `Package` link instance
2. Enter this package using `space` menu
3. Create `TSX` link instance
4. Click on `Contain` link instance to activate `stringClientHandler`

### Workaround

Use `editor` menu instead.

**Comment by ivansglazunov** [comment]
Not only in package. Finder override any handler. I take this bug.

**Comment by Konard** [comment]
Done by @ivansglazunov : https://discord.com/channels/739430470345031692/1191768842909786282/1192001337009905684
